mysql:
  path: rm-cn-x0r395x3e0007aeo.rwlb.rds.aliyuncs.com
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: whiteboard
  username: baoguoqiang
  password: Tiger!2023
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
jwt:
  signing-key: 2d260498-5a22-416c-8694-783845b52900
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus
